<a href="https://colab.research.google.com/github/Edersao/Curso_Data_Scientist/blob/main/prueba_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Prueba: matrices

1. Crea un arreglo de numpy llamado listaDatos con los sgueintes valores:
[45, 67, 23, 51, 89, 100, 23, 46, 57, 12, 1, 87, 23, 69, 33, 18, 87, 45, 73, 28]

In [1]:
import numpy as np

In [8]:
listDatos=np.array([45, 67, 23, 51, 89, 100, 23, 46, 57, 12, 1, 87, 23, 69, 33, 18, 87, 45, 73, 28])

2. Crea una matriz de numpy de 5x4 llamada matrizA con los sigueintes valores:
[[34, 61, 0, 12], [98, 53, 76, 2], [19, 56, 87, 32], [100, 62, 91, 21], [84, 50,41, 3]]

In [9]:
matrizA= np.array([[34, 61, 0, 12], [98, 53, 76, 2], [19, 56, 87, 32], [100, 62, 91, 21], [84, 50,41, 3]])
print(matrizA)

[[ 34  61   0  12]
 [ 98  53  76   2]
 [ 19  56  87  32]
 [100  62  91  21]
 [ 84  50  41   3]]


3. Convierte el arreglo **listDatos** a una matriz 5x4 llamada matrizB.

In [26]:
matrizB=listDatos.reshape(5,4)
print(listDatos, matrizB, sep='\n')

[ 45  67  23  51  89 100  23  46  57  12   1  87  23  69  33  18  87  45
  73  28]
[[ 45  67  23  51]
 [ 89 100  23  46]
 [ 57  12   1  87]
 [ 23  69  33  18]
 [ 87  45  73  28]]


4. Determina el valor mínimo y máximo de la matrizA.

In [16]:
print("Valor minimo de la matrizA: \n", matrizA.min())
print("Valor maximo de la matrizA: \n", matrizA.max())

Valor minimo de la matrizA: 
 0
Valor maximo de la matrizA: 
 100


5. Calcula el promedio de cada una de las columnas de la matrizA

In [17]:
print("Valor promedio de columnas de la matrizA: \n", matrizA.mean(axis=0))

Valor promedio de columnas de la matrizA: 
 [67.  56.4 59.  14. ]


6. Calcula la suma de todos los elementos de la segunda y tercera fila de la **matrizA**

In [28]:
print("Suma de los elementos de la segunda fila: \n", matrizA[1].sum())
print("Suma de los elementos de la tercera fila: \n", matrizA[2].sum())
print("suma de los elemtos de la seugnda ya tercera fila: \n", matrizA[1].sum()+matrizA[2].sum())

Suma de los elementos de la segunda fila: 
 229
Suma de los elementos de la tercera fila: 
 194
suma de los elemtos de la seugnda ya tercera fila: 
 423
875


7. Suma las dos matrices

In [23]:
matrizA+matrizB

array([[ 79, 128,  23,  63],
       [187, 153,  99,  48],
       [ 76,  68,  88, 119],
       [123, 131, 124,  39],
       [171,  95, 114,  31]])

8. Redimensiona la **matrizB** a un tamaño 4x5 y obtén la multimplicación de la **matrizA** por la **matrizB**

In [24]:
matrizB= matrizB.reshape(4,5)
matrizA @ matrizB

array([[ 7846,  4725,  4128,  6087,  4094],
       [ 9822, 14571,  6530, 13409, 11922],
       [ 7118, 12914,  6454, 12500,  6130],
       [11169, 17870,  8190, 16446, 13235],
       [ 8875, 10606,  5310, 10182,  9513]])

9. Obten la transpuesta de la **matrizB**

In [32]:
print(matrizB.transpose())

[[ 45  89  57  23  87]
 [ 67 100  12  69  45]
 [ 23  23   1  33  73]
 [ 51  46  87  18  28]]
